name: Validator

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  RUBY_VERSION: '2.6'

defaults:
  run:
    shell: bash

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install gem
        run: |
          gem install awesome_bot

      - name: Validate
        run: |
          awesome_bot README.md --request-delay 0.5 --allow-timeout --allow-redirect \
          -w https://github.com/ehsanmok/awesome-infrastructure-from-code/actions/workflows/validator.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          if-no-files-found: warn
          name: ab-results
          path: |
            ab-results-README.md.json
            ab-results-README.md-filtered.json
            ab-results-README.md-markdown-table.json
