name: Validator

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  RUBY_VERSION: '2.6'

defaults:
  run:
    shell: bash

jobs:
  validator:
    name: Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

    - id: install-gem
      name: Install gem
      run: |
        gem install awesome_bot

    - id: validate
      name: Validate
      run: |
        awesome_bot README.md --request-delay 0.5 --allow-timeout --allow-redirect

    - id: upload-artifact
      name: Upload artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        if-no-files-found: warn
        name: failed-results
        path: |
          failed-results-README.md.json
          failed-results-README.md-filtered.json
          failed-results-README.md-markdown-table.json
